[workspace]
members = ["fast-tlsh", "fast-tlsh/serde-tests"]
resolver = "3"

[workspace.package]
version = "0.2.0-alpha.3"
edition = "2024"
rust-version = "1.85"

[profile.release]
opt-level = 3
codegen-units = 1
debug = true
